name: ci
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Create build directory
        run: mkdir build
      - name: Run CMake
        run: cmake ../
        working-directory: ./build
      - name: Build targets
        if: ${{ matrix.os != 'windows-latest' }}
        run: make -j$(nproc)
        working-directory: ./build
      - name: Build targets
        if: ${{ matrix.os == 'windows-latest' }}
        run: MSBuild.exe litecrypt.sln
        working-directory: ./build
      - name: Test
        run: ./litecrypt_test
        working-directory: ./build
