name: litecrypt-ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print info
        run: echo "$GITHUB_WORKSPACE"
      - name: Create build folder
        run: mkdir $GITHUB_WORKSPACE/build
      - name: Run CMake
        run: |
          pwd
          ls
          cmake $GITHUB_WORKSPACE
      - name: Make targets
        run: make -j$(nproc)
        working-directory: $GITHUB_WORKSPACE/build