name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create build directory
        run: mkdir $GITHUB_WORKSPACE/build
      - name: Run CMake
        run: cmake ../
        working-directory: ${{ github.workspace	}}/build
      - name: Make targets
        run: make -j$(nproc)
        working-directory: ${{ github.workspace	}}/build
      - name: Test
        run: ./litecrypt_test
        working-directory: ${{ github.workspace	}}/build
